/*
 * TIMER0_config.h
 *
 *  Created on: Oct 27, 2023
 *      Author: Ebram Habib
 */

#ifndef TIMER0_CONFIG_H_
#define TIMER0_CONFIG_H_

typedef enum{
	TIMER0_NORMAL_MODE = 0,
	TIMER0_PHASE_CORRECT_PWM_MODE = 1,
	TIMER0_CTC_MODE = 2,
	TIMER0_FAST_PWM_MODE = 3
}TIMER0_MODE;

typedef enum{
	TIMER0_COMPARE_OUTPUT_NON_PWM_MODE_OC0_DISCONNECTED = 0,
	TIMER0_COMPARE_OUTPUT_NON_PWM_MODE_OC0_TOGGLE = 1,
	TIMER0_COMPARE_OUTPUT_NON_PWM_MODE_OC0_CLEAR = 2,
	TIMER0_COMPARE_OUTPUT_NON_PWM_MODE_OC0_SET = 3
}TIMER0_COMPARE_OUTPUT_NON_PWM_MODE;

typedef enum{
	TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE_OC0_DISCONNECTED = 0,
	TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE_RESERVED = 1,
	TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE_OC0_CLEAR = 2,
	TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE_OC0_SET = 3
}TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE;

typedef enum{
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE_OC0_DISCONNECTED = 0,
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE_RESERVED = 1,
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE_OC0_CLEAR = 2,
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE_OC0_SET = 3
}TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE;

typedef enum{
TIMER0_FCPU_DIVIDED_BY_1=1,
TIMER0_FCPU_DIVIDED_BY_8,
TIMER0_FCPU_DIVIDED_BY_64,
TIMER0_FCPU_DIVIDED_BY_256,
TIMER0_FCPU_DIVIDED_BY_1024,
TIMER0_EXTERNAL_SOURCE_FALLING_EDGE,
TIMER0_EXTERNAL_SOURCE_RISING_EDGE
}TIMER0_CLOCK_SELECT;


typedef struct{
	TIMER0_COMPARE_OUTPUT_NON_PWM_MODE 				Compare_output_Non_PWM;
	TIMER0_COMPARE_OUTPUT_FAST_PWM_MODE				Compare_output_Fast_PWM;
	TIMER0_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE	Compare_output_Phase_Correct_PWM;
	TIMER0_CLOCK_SELECT 							Clock_Select;
	TIMER0_MODE 									Mode;
	u8 TIMER0_INITIAL_VALUE;
	u8 TIMER0_COMPARE_VALUE;
}TIMER0_INIT_CONFIG;

#define TIMER0_TICK_TIME 128

#endif /* TIMER0_CONFIG_H_ */
