/*
 * ULTRASONIC_prog.c
 *
 *  Created on: Oct 30, 2023
 *      Author: Ebram Habib
 */
#include "std_types.h"
#include "common_macros.h"
#include "GPIO_Int.h"
#include "GIE_int.h"
#include "TIMER1_int.h"
#include "ULTRASONIC_int.h"
#include "ULTRASONIC_config.h"
#include <avr/delay.h>
#include "TIMER1_priv.h"

u8 g_count = 0;
u16 g_time = 0;

TIMER1_INIT_CONFIG TIMER1_config = {
		TIMER1_COMPARE_OUTPUT_NON_PWM_MODE_OC1A_OC1B_DISCONNECTED,
		TIMER1_COMPARE_OUTPUT_FAST_PWM_MODE_OC1A_OC1B_SET,
		TIMER1_COMPARE_OUTPUT_PHASE_CORRECT_PWM_MODE_OC1A_OC1B_DISCONNECTED,
		FCPU_DIVIDED_BY_8,
		TIMER1_NORMAL_MODE,
		0,
		0
};

/*
 * • Description
➢ Initialize the ICU driver as required.
➢ Setup the ICU call back function.
➢ Setup the direction for the trigger pin as output pin through the
GPIO driver.
• Inputs: None
• Return: None
 */

void Ultrasonic_init(void)
{

	TIMER1_Init(&TIMER1_config);
	TIMER1_GetEventDuration();
	TIMER1_SetCallBack(Ultrasonic_edgeProcessing);
	TIMER1_Start(&TIMER1_config);

	DIO_voidSetPinDirection(pPORTD, pin6, input);

	DIO_voidSetPinDirection(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PIN, output);
	DIO_voidSetPinValue(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description
➢ Send the Trigger pulse to the ultrasonic.
• Inputs: None
• Return: None
*/

void Ultrasonic_Trigger(void)
{
	DIO_voidSetPinValue(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PIN, LOGIC_HIGH);
//	TIMER1_SetDelayTimeMilliSec(&TIMER1_config,1);
	_delay_us(10);
	DIO_voidSetPinValue(ULTRASONIC_TRIGGER_PORTID, ULTRASONIC_TRIGGER_PIN, LOGIC_LOW);
}

/*
 * Description
➢ Send the trigger pulse by using Ultrasonic_Trigger function.
➢ Start the measurements by the ICU from this moment.
• Inputs: None
• Return: The measured distance in Centimeter.
*/

u16  Ultrasonic_readDistance(void)
{
	static u16 distance = 0;

	if(g_count == 0)
	{
		Ultrasonic_Trigger();	/* sending the triggering signal to the sensor */
	}
	else if(g_count == 2)
	{
		distance = (g_time / 57.7);
		g_count = 0;
	}
	return distance;

}

/*
 * Description
➢ This is the call back function called by the ICU driver.
➢ This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
• Inputs: None
• Return: None
*/

void Ultrasonic_edgeProcessing(void)
{
	if(g_count == 0)
	{
		g_time = TIMER1_GetInputCaptureValue();
		g_count++;
		TIMER1_SetInputCaptureEdgeDetection(FALLING_EDGE);
	}
	else if(g_count == 1)
	{
		g_time = TIMER1_GetInputCaptureValue() - g_time;
		TIMER1_ClearTimerValue();
		g_count++;
		TIMER1_SetInputCaptureEdgeDetection(RISING_EDGE);
	}
}

void Ultrasonic_disable(void)
{
	TIMER1_DisableICU();
}

void Ultrasonic_enable(void)
{
	TIMER1_EnableICU();
}
